// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Package = {
  /**
   * 包名，推荐仅使用英文、中文和空格。
   * 不得包含下划线（`_`），请使用空格或横杠线（`-`）代替。
   */
  name: string;
  /**
   * 包的简短描述，尽量从官方渠道摘取简介。
   */
  description: string;
  /**
   * 包模板，当前版本中仅能为 "Software"。
   */
  template: string;
  /**
   * 包版本号，使用 ExSemVer 规范。
   * ExSemVer 规范在 [SemVer](https://semver.org) 的基础上在`PATCH`和`PRE`之间增加了一位`RESERVED`位，用于标记不同的打包版本，或是用来兼容在 Windows 平台常见的 4 位版本号；若上游版本号符合 SemVer 规范则将`RESERVED`位置`0`即可。
   */
  version: string;
  /**
   * 包作者，第一作者应为打包者，后面通常跟发行商、制作方。
   * 支持使用 `<>` 包裹作者邮箱。
   */
  authors: Array<string>;
  /**
   * 开源许可证的 [SPDX 标识符](https://spdx.org/licenses/)或 EULA 链接。
   */
  license: string | null;
  /**
   * 包图标 URL。
   */
  icon: string | null;
  /**
   * 是否使用严格模式，缺省为`true`。
   * 启用严格模式时，如果某一步骤出错则工作流会立即停止执行并报告错误；否则工作流只会对错误进行警告然后继续运行后续步骤。
   *
   * :::warning
   * 注意如果希望使用内置变量[`ExitCode`](/nep/definition/2-context#exitcode)，请将`strict`设置为`false`。
   * :::
   */
  strict: boolean | null;
};
