name = "official"
locale = "zh-CN"
description = "Official nep mirror"
maintainer = "Edgeless"
protocol = "1.0.0"
root_url = "https://registry.edgeless.top"

service = [
    { key = "HELLO", path = "/hello" },
    { key = "PKG_SOFTWARE", path = "/nep" },
]

[property]
deploy_region = "zh-CN"
proxy_storage = true
upload_bandwidth = 1000
sync_interval = 0

[proxy]
typeKey = "AList"
rootUrl = "https://zfile.edgeless.top"
