name = "official"
locale = "zh-CN"
description = "Official nep mirror"
maintainer = "Edgeless"
protocol = "1.0.0"
root_url = "http://localhost:3000"

service = [
    { key = "PKG_SOFTWARE", path = "/nep" }
]

[property]
deploy_region = "zh-CN"
proxy_storage = true
upload_bandwidth = 1000
sync_interval = 0

[proxy]
typeKey = "AList"
rootUrl = "https://zfile.edgeless.top"